# Generated by Django 2.1 on 2020-06-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zhipin',
            fields=[
                ('id', models.AutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('wages', models.CharField(blank=True, max_length=255, null=True)),
                ('technology', models.CharField(blank=True, max_length=255, null=True)),
                ('coustompage', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'zhipin',
                'managed': False,
            },
        ),
    ]
